### ISSUE TITLE
Failed to serialize org.datadog.jenkins.plugins.datadog.model.PipelineQueueInfoAction occasionally thrown during pipeline execution

### ISSUE THREAD

**Issue by tamir-allc** [jenkinsci/datadog-plugin#284]
**Describe the bug**
Occasionally an error about 'failed to serialization' is thrown by the Datadog plugin during the jenkins job.
Ever since we installed the DD plugin, it errors out once in a while.
Removing the plugin obviously fixes it but we do want to use the DD<->Jenkins integration to fully utilize our monitoring capabilities.

**Expected behavior**
This error will not be thrown.

**Environment and Versions (please complete the following information):**
- Jenkins version 2.319.1
- Datadog Plugin version 3.5.1
- We use a shared library for the pipelines
- DD site is hosted in EU region.
- The datadog.yaml and the plugin are configured correctly. The plugin prints out success messages to both the CI visibility and Log tests.

**Additional context**

Log:
```
Running on Jenkins in /opt/bitnami/apps/jenkins/jenkins_home/workspace/randomfoldername/randomjobname
[Pipeline] {
[Pipeline] unstash
[Pipeline] readFile
[Pipeline] readProperties
[Pipeline] }
[Pipeline] // node
[Pipeline] node
[Pipeline] End of Pipeline
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1479)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1477)
	at com.thoughtworks.xstream.converters.collections.MapConverter.marshal(MapConverter.java:75)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:278)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:265)
Caused: java.lang.RuntimeException: Failed to serialize org.datadog.jenkins.plugins.datadog.model.PipelineQueueInfoAction#queueDataByFlowNode for class org.datadog.jenkins.plugins.datadog.model.PipelineQueueInfoAction
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:269)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:236)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:174)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:221)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:160)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:87)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeBareItem(AbstractCollectionConverter.java:94)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:66)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeCompleteItem(AbstractCollectionConverter.java:81)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:74)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:278)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:265)
Caused: java.lang.RuntimeException: Failed to serialize hudson.model.Actionable#actions for class org.jenkinsci.plugins.workflow.job.WorkflowRun
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:269)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:236)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:174)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:221)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:160)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1243)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1232)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:1205)
	at hudson.util.XStream2.toXMLUTF8(XStream2.java:325)
	at org.jenkinsci.plugins.workflow.support.PipelineIOUtils.writeByXStream(PipelineIOUtils.java:34)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.save(WorkflowRun.java:1218)
	at hudson.BulkChange.commit(BulkChange.java:97)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.notifyListeners(CpsFlowExecution.java:1485)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$3.run(CpsThreadGroup.java:491)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:38)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

It's gotta be related to concurrency and parallelism.
Perhaps the https://github.com/jenkinsci/datadog-plugin/blob/c1454b6a99aed5e0447384c3d9d827649b17af7e/src/main/java/org/datadog/jenkins/plugins/datadog/model/PipelineQueueInfoAction.java#L6 should be ConcurrentHashMap instead of HashMap?

Thanks!

**Comment by drodriguezhdez** [comment]
Thanks @tamir-allc for reporting this. A similar issue appeared in the past. A fix is on its way https://github.com/jenkinsci/datadog-plugin/pull/286

**Comment by tamir-allc** [comment]
@drodriguezhdez Great. Appreciate the quick response. Looking forward for the new release containing this fix.

**Comment by drodriguezhdez** [comment]
@tamir-allc the new 3.5.2 version should have fixed this issue. Thanks!
