### ISSUE TITLE
Latest plugin version causing exception in system log, when no API token configured

### ISSUE THREAD

**Issue by marmccor** [jenkinsci/datadog-plugin#42]
**Description**
Whenever an API token is not configured for the datadog plugin, the following output is repeatedly output to the Jenkins system log:
```
eb 03, 2020 4:27:37 PM SEVERE org.datadog.jenkins.plugins.datadog.clients.DatadogHttpClient getInstance
Datadog API Key is not set properly
Feb 03, 2020 4:27:37 PM SEVERE org.datadog.jenkins.plugins.datadog.DatadogUtilities severe
An unexpected error occurred: java.lang.RuntimeException: Datadog API Key is not set properly
	at org.datadog.jenkins.plugins.datadog.clients.DatadogHttpClient.getInstance(DatadogHttpClient.java:89)
	at org.datadog.jenkins.plugins.datadog.clients.ClientFactory.getClient(ClientFactory.java:38)
	at org.datadog.jenkins.plugins.datadog.clients.ClientFactory.getClient(ClientFactory.java:60)
	at org.datadog.jenkins.plugins.datadog.listeners.DatadogSaveableListener.onChange(DatadogSaveableListener.java:61)
	at hudson.model.listeners.SaveableListener.fireOnChange(SaveableListener.java:81)
	at jenkins.model.Jenkins.save(Jenkins.java:3318)
	at hudson.model.Saveable$save.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at 1-initMasterBaseConfiguration.run(1-initMasterBaseConfiguration.groovy:30)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:585)
	at jenkins.util.groovy.GroovyHookScript.execute(GroovyHookScript.java:136)
	at jenkins.util.groovy.GroovyHookScript.execute(GroovyHookScript.java:127)
	at jenkins.util.groovy.GroovyHookScript.run(GroovyHookScript.java:110)
	at hudson.init.impl.GroovyInitScript.init(GroovyInitScript.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1121)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
**Regression?**
This looks like a regression in the latest plugin version (either 1.0.2 or 1.0.1). v 1.0.0 does not show this behaviour, and I have been able to confirm and get a repo of this on multiple different Jenkins masters. 

**To Reproduce**
1. Install (or upgrade) to latest datadog plugin
2. Don't configure an API token for datadog in the jenkins configuration
3. Observe the output in the system log

**Environment and Versions (please complete the following information):**
- Jenkins v 2.204.2 (also repo on v 2.204.1)
- Datadog plugin 1.02

**Comment by FnTm** [comment]
I also observed this kind of behaviour, and for us it just meant that data suddenly stopped coming into DataDog, where it was succesfuly being sent to with the previous version of the plugin. So something broke in this version

**Comment by gzussa** [comment]
Fixed in https://github.com/jenkinsci/datadog-plugin/pull/44 and will be part of the next release (1 or 2 weeks from now)
